# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/pynewsreader',
                'doc_host': 'https://radinplaid.github.io',
                'git_url': 'https://github.com/radinplaid/pynewsreader',
                'lib_path': 'pynewsreader'},
  'syms': { 'pynewsreader.core': { 'pynewsreader.core.PyNewsReader': ('core.html#pynewsreader', 'pynewsreader/core.py'),
                                   'pynewsreader.core.PyNewsReader.__init__': ('core.html#pynewsreader.__init__', 'pynewsreader/core.py'),
                                   'pynewsreader.core.PyNewsReader.print_entries': ( 'core.html#pynewsreader.print_entries',
                                                                                     'pynewsreader/core.py'),
                                   'pynewsreader.core.PyNewsReader.search': ('core.html#pynewsreader.search', 'pynewsreader/core.py'),
                                   'pynewsreader.core.PyNewsReader.search_to_entry': ( 'core.html#pynewsreader.search_to_entry',
                                                                                       'pynewsreader/core.py'),
                                   'pynewsreader.core.PyNewsReader.show': ('core.html#pynewsreader.show', 'pynewsreader/core.py'),
                                   'pynewsreader.core.PyNewsReader.update': ('core.html#pynewsreader.update', 'pynewsreader/core.py'),
                                   'pynewsreader.core.strip_html': ('core.html#strip_html', 'pynewsreader/core.py')}}}
