# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/pynewsreader',
                'doc_host': 'https://radinplaid.github.io',
                'git_url': 'https://github.com/radinplaid/pynewsreader',
                'lib_path': 'pynewsreader'},
  'syms': {'pynewsreader.core': {'pynewsreader.core.strip_html': ('core.html#strip_html', 'pynewsreader/core.py')}}}
